// multiply indexes with 5
// 1.Array Mapping

// let array = [1,2,3,4,5];
// let array1 = array.map((element)=>{
//     return element*5;
// })
// console.log(array1);

// 2.array of Object Mapping

// let student =[
//     {name : "bakya",age : 23},
//     {name: "mani", age :24},
//     {name: "atshuma", age :21},
//     {name: "kishore", age :19}
//     ]; 
//     let student23 = student.map((element)=>{
//         element.age += 5;
//         return element;
//     });
//     console.log(student23);


// Filet method

// let student =[
//     {name: "bakya",age : 23},
//     {name: "mani", age :24},
//     {name: "atshuma", age :21},
//     {name: "kishore", age :19}
//     ]; 
//     let result = student.filter((element)=>{
//       let bi= element.age >= 23 ;
//       return bi;
//     });
//     console.log(result);
    
//     var a = [1,2,3,4,5,6,7,8,9];
//     let result = a.filter((element)=>{
//         return element%2 != 0;
//     } )
// console.log(result);

// reduce method

// let array3 = [1,2,3,4,5,2];
// let result3 = array3.reduce((acc,cur)=>{
//     return acc*cur;
// });
// console.log(result3);


// let total = 30000;
// let array4 =[10000,2000,400,750];
// let balance = array4.reduce((acc,cur)=>
//   acc+cur, total
    
// )
// console.log(balance);


 


</html>